version: "3"

services:
  api:
    build: ./api
    container_name: api
    restart: always
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      HOST: http://localhost
      MONGODB_URL: mongodb://api_db:27017/api
    volumes:
      - ./api:/app
    depends_on:
      - api_db

  api_db:
    image: mongo:latest
    container_name: api_db
    restart: always
    ports:
      - "27017:27017"
