version: "3"

services:
  api:
    build: ./api
    container_name: api
    restart: always
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      HOST: http://localhost
    volumes:
      - ./api:/app
